# Header
menu:	#站点左上角导航栏
  首页: /
  存档: /archives
rss: /atom.xml		#RSS,需要配置路径

# Content	
excerpt_link: 阅读更多...
fancybox: true	#图片效果

# Sidebar	#侧边栏
sidebar: right
widgets:
- category
- recent_posts
- links
- tagcloud
- mp3player

# Miscellaneous
google_analytics:
favicon: /z.png
twitter:
google_plus:
fb_admins:
fb_app_id:

#duoshuo
duoshuo: 
